In [16]:
from matplotlib import pyplot as plt
from scipy import stats
import numpy as np
import pandas as pd
#from pathlib import Path

In [21]:


#data_df = Path("Resources/us_states_covid19_daily.csv")

data_df = pd.read_csv("Resources/us_states_covid19_daily.csv")
data_df

,date,state,positive,probableCases,negative,pending,totalTestResultsSource,totalTestResults,hospitalizedCurrently,hospitalizedCumulative,...,posNeg,deathIncrease,hospitalizedIncrease,hash,commercialScore,negativeRegularScore,negativeScore,positiveScore,score,grade
0,20201206,AK,35720.0,NaN,1042056.0,NaN,totalTestsViral,1077776.0,164.0,799.0,...,1077776,0,0,7b1d31e2756687bb9259b29195f1db6cdb321ea6,0,0,0,0,0,NaN
1,20201206,AL,269877.0,45962.0,1421126.0,NaN,totalTestsPeopleViral,1645041.0,1927.0,26331.0,...,1691003,12,0,19454ed8fe28fc0a7948fc0771b2f3c846c1c92e,0,0,0,0,0,NaN
2,20201206,AR,170924.0,22753.0,1614979.0,NaN,totalTestsViral,1763150.0,1076.0,9401.0,...,1785903,40,21,25fc83bffff5b32ba1a737be8e087fad9f4fde33,0,0,0,0,0,NaN
3,20201206,AS,0.0,NaN,2140.0,NaN,totalTestsViral,2140.0,NaN,NaN,...,2140,0,0,8c39eec317586b0c34fc2903e6a3891ecb00469e,0,0,0,0,0,NaN
4,20201206,AZ,364276.0,12590.0,2018813.0,NaN,totalTestsPeopleViral,2370499.0,2977.0,28248.0,...,2383089,25,242,7cf59da9e4bc31d905e179211313d08879880a85,0,0,0,0,0,NaN
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
15628,20200124,WA,0.0,NaN,0.0,NaN,totalTestEncountersViral,0.0,NaN,NaN,...,0,0,0,82726df68eb97c98a4a6ee792349e547023147d5,0,0,0,0,0,NaN
15629,20200123,MA,NaN,NaN,NaN,NaN,totalTestsViral,2.0,NaN,NaN,...,0,0,0,76bc987d054b119a4e05a4a43742249c0b0568b6,0,0,0,0,0,NaN
15630,20200123,WA,0.0,NaN,0.0,NaN,totalTestEncountersViral,0.0,NaN,NaN,...,0,0,0,1c2229c239ffad5e5fdd9d76c641dc9166caf6ba,0,0,0,0,0,NaN
15631,20200122,MA,NaN,NaN,NaN,NaN,totalTestsViral,1.0,NaN,NaN,...,0,0,0,01f5dcd6631859503ef1b62d81d49e41d12fc1bd,0,0,0,0,0,NaN
15632,20200122,WA,0.0,NaN,0.0,NaN,totalTestEncountersViral,0.0,NaN,NaN,...,0,0,0,4502685e582e68071bfe8f7e1b307bc09c16728d,0,0,0,0,0,NaN

In [19]:
data_df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 15633 entries, 0 to 15632
Data columns (total 55 columns):
 #   Column                       Non-Null Count  Dtype
---  ------                       --------------  -----
 0   date                         15633 non-null  int64
 1   state                        15633 non-null  object
 2   positive                     15481 non-null  float64
 3   probableCases                5449 non-null   float64
 4   negative                     15323 non-null  float64
 5   pending                      1684 non-null   float64
 6   totalTestResultsSource       15633 non-null  object
 7   totalTestResults             15598 non-null  float64
 8   hospitalizedCurrently        12516 non-null  float64
 9   hospitalizedCumulative       9434 non-null   float64
 10  inIcuCurrently               7713 non-null   float64
 11  inIcuCumulative              2700 non-null   float64
 12  onVentilatorCurrently        6211 non-null   float64
 13  onVentilatorCumulative       929 non-null    float64
 14  recovered                    11111 non-null  float64
 15  dataQualityGrade             14372 non-null  object
 16  lastUpdateEt                 15146 non-null  object
 17  dateModified                 15146 non-null  object
 18  checkTimeEt                  15146 non-null  object
 19  death                        14807 non-null  float64
 20  hospitalized                 9434 non-null   float64
 21  dateChecked                  15146 non-null  object
 22  totalTestsViral              9821 non-null   float64
 23  positiveTestsViral           5012 non-null   float64
 24  negativeTestsViral           3315 non-null   float64
 25  positiveCasesViral           12117 non-null  float64
 26  deathConfirmed               6850 non-null   float64
 27  deathProbable                5104 non-null   float64
 28  totalTestEncountersViral     3678 non-null   float64
 29  totalTestsPeopleViral        6628 non-null   float64
 30  totalTestsAntibody           3017 non-null   float64
 31  positiveTestsAntibody        2218 non-null   float64
 32  negativeTestsAntibody        995 non-null    float64
 33  totalTestsPeopleAntibody     1258 non-null   float64
 34  positiveTestsPeopleAntibody  799 non-null    float64
 35  negativeTestsPeopleAntibody  768 non-null    float64
 36  totalTestsPeopleAntigen      544 non-null    float64
 37  positiveTestsPeopleAntigen   411 non-null    float64
 38  totalTestsAntigen            1177 non-null   float64
 39  positiveTestsAntigen         731 non-null    float64
 40  fips                         15633 non-null  int64
 41  positiveIncrease             15633 non-null  int64
 42  negativeIncrease             15633 non-null  int64
 43  total                        15633 non-null  int64
 44  totalTestResultsIncrease     15633 non-null  int64
 45  posNeg                       15633 non-null  int64
 46  deathIncrease                15633 non-null  int64
 47  hospitalizedIncrease         15633 non-null  int64
 48  hash                         15633 non-null  object
 49  commercialScore              15633 non-null  int64
 50  negativeRegularScore         15633 non-null  int64
 51  negativeScore                15633 non-null  int64
 52  positiveScore                15633 non-null  int64
 53  score                        15633 non-null  int64
 54  grade                        0 non-null      float64
dtypes: float64(33), int64(14), object(8)
memory usage: 6.6+ MB

In [20]:
data_df.columns

Index(['date', 'state', 'positive', 'probableCases', 'negative', 'pending',
       'totalTestResultsSource', 'totalTestResults', 'hospitalizedCurrently',
       'hospitalizedCumulative', 'inIcuCurrently', 'inIcuCumulative',
       'onVentilatorCurrently', 'onVentilatorCumulative', 'recovered',
       'dataQualityGrade', 'lastUpdateEt', 'dateModified', 'checkTimeEt',
       'death', 'hospitalized', 'dateChecked', 'totalTestsViral',
       'positiveTestsViral', 'negativeTestsViral', 'positiveCasesViral',
       'deathConfirmed', 'deathProbable', 'totalTestEncountersViral',
       'totalTestsPeopleViral', 'totalTestsAntibody', 'positiveTestsAntibody',
       'negativeTestsAntibody', 'totalTestsPeopleAntibody',
       'positiveTestsPeopleAntibody', 'negativeTestsPeopleAntibody',
       'totalTestsPeopleAntigen', 'positiveTestsPeopleAntigen',
       'totalTestsAntigen', 'positiveTestsAntigen', 'fips', 'positiveIncrease',
       'negativeIncrease', 'total', 'totalTestResultsIncrease', 'posNeg',
       'deathIncrease', 'hospitalizedIncrease', 'hash', 'commercialScore',
       'negativeRegularScore', 'negativeScore', 'positiveScore', 'score',
       'grade'],
      dtype='object')

In [22]:
daily_data = pd.read_csv("Resources/us_covid19_daily.csv")

daily_data

,date,states,positive,negative,pending,hospitalizedCurrently,hospitalizedCumulative,inIcuCurrently,inIcuCumulative,onVentilatorCurrently,...,totalTestResults,lastModified,total,posNeg,deathIncrease,hospitalizedIncrease,negativeIncrease,positiveIncrease,totalTestResultsIncrease,hash
0,20201206,56,14534035,161986294,13592.0,101487.0,585676.0,20145.0,31946.0,7094.0,...,204063869,2020-12-06T24:00:00Z,0,0,1138,2256,1172590,176771,1634532,9cf16504f91958e803a2197daf8c2528a4eddc18
1,20201205,56,14357264,160813704,13433.0,101190.0,583420.0,19950.0,31831.0,7005.0,...,202429337,2020-12-05T24:00:00Z,0,0,2445,3316,1526995,211073,2169756,6249216c5f097c94ce33a811dab011a483a42404
2,20201204,56,14146191,159286709,12714.0,101276.0,580104.0,19858.0,31608.0,6999.0,...,200259581,2020-12-04T24:00:00Z,0,0,2563,4652,1260657,224831,1854869,ae30ea088584335ba4d57ee927f8dbda6add74db
3,20201203,56,13921360,158026052,15106.0,100755.0,575452.0,19723.0,31276.0,6867.0,...,198404712,2020-12-03T24:00:00Z,0,0,2706,5331,1238465,210204,1828230,0f253d185ecb336cdd18a4c61996eda1b7eef13b
4,20201202,56,13711156,156787587,14368.0,100322.0,570121.0,19680.0,31038.0,6855.0,...,196576482,2020-12-02T24:00:00Z,0,0,2733,5028,982032,195796,1459202,477c17b6302d0485195e77ecf8270a974f7a3c82
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
315,20200126,2,0,0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,2020-01-26T24:00:00Z,0,0,0,0,0,0,0,69c67c81e64d10a5270497fc5336779c06fb812b
316,20200125,2,0,0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,2020-01-25T24:00:00Z,0,0,0,0,0,0,0,9ea5731f5b0a79617b994d6842eecfdbeb1dde35
317,20200124,2,0,0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,2020-01-24T24:00:00Z,0,0,0,0,0,0,0,287531342bc8d5f2650b0cc12ebcca3807a64b7b
318,20200123,2,0,0,NaN,NaN,NaN,NaN,NaN,NaN,...,2,2020-01-23T24:00:00Z,0,0,0,0,0,0,1,e0563aac8e1bc7b8b8059c52831b97179ff6f981
319,20200122,2,0,0,NaN,NaN,NaN,NaN,NaN,NaN,...,1,2020-01-22T24:00:00Z,0,0,0,0,0,0,0,e0caa1c66c4aa83baf227afe12261a1493fc0d7e

In [23]:
counties_data = pd.read_csv("Resources/us_counties_covid19_daily.csv")
counties_data

              date      county       state     fips  cases  deaths
0       2020-01-21   Snohomish  Washington  53061.0      1     0.0
1       2020-01-22   Snohomish  Washington  53061.0      1     0.0
2       2020-01-23   Snohomish  Washington  53061.0      1     0.0
3       2020-01-24        Cook    Illinois  17031.0      1     0.0
4       2020-01-24   Snohomish  Washington  53061.0      1     0.0
...            ...         ...         ...      ...    ...     ...
800432  2020-12-05  Sweetwater     Wyoming  56037.0   2098    10.0
800433  2020-12-05       Teton     Wyoming  56039.0   1739     2.0
800434  2020-12-05       Uinta     Wyoming  56041.0   1187     5.0
800435  2020-12-05    Washakie     Wyoming  56043.0    519     8.0
800436  2020-12-05      Weston     Wyoming  56045.0    419     2.0

[800437 rows x 6 columns]